name: version-check
on: push
  # pull_request:
  #   types:
  #     - opened
env:
  BASE_REF: origin/${{ github.base_ref }}
  HEAD_REF: origin/${{ github.head_ref }}
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: test
        run: |
          echo base "$BASE_REF"
          echo  target "$TARGET_REF"
      - name: version_read
        run: bash .github/workflows/src/version_read.sh
        id: version_read
      - name: version_check
        if: ${{ steps.version_read.output.VERSION }}
        run: |
          echo "Tag name ${{  github.ref_name }}"
        
