name: version-check
on: 
  pull_request_target:
      types: [assigned, opened, synchronize, reopened]
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: test-env
        run: |
          echo start
          echo base ref "$GITHUB_BASE_REF"
          echo ref "$GITHUB_REF"
      - name: version_read
        run: bash .github/workflows/src/version_read.sh
        id: version_read
      - name: version_check
        if: ${{ steps.version_read.output.VERSION }}
        run: |
          echo "Tag name ${{  github.ref_name }}"
        
