name: version-check
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setting env variables
        run: |
          echo "HEAD_REF=origin/$GITHUB_HEAD_REF" >> "$GITHUB_ENV"
          echo "BASE_REF=origin/$GITHUB_BASE_REF" >> "$GITHUB_ENV"
      - name: version_check
        run: bash .github/workflows/src/version_read.sh
        