name: version-check
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setting env variables
        run: |
          echo "HEAD_REF=origin/$GITHUB_HEAD_REF" >> "$GITHUB_ENV"
          echo "BASE_REF=origin/$GITHUB_BASE_REF" >> "$GITHUB_ENV"
      - name: test-env
        run: |
          echo start
          echo head ref "$HEAD_BRANCH"  
          echo base name "$BASE_BRANCH"
      - name: version_read
        run: bash .github/workflows/src/version_read.sh
        id: version_read
      - name: version_check
        if: ${{ steps.version_read.output.VERSION }}
        run: |
          echo "Tag name ${{  github.ref_name }}"
        
